import { Menu } from './menu';

export const MENU: Menu[] = [
    {
        id: 1,
        nombre: 'huds',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'historial',
        target: 'miHuds',
        link: 'miHuds',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 2,
        nombre: 'consultas',
        tipo: 'custom',
        semanticTag: 'solicitud',
        icono: 'mano-corazon',
        target: 'misConsultas',
        link: 'misConsultas',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 11,
        nombre: 'documentos',
        tipo: 'info',
        semanticTag: 'registro',
        icono: 'documento-cursor',
        target: 'misDocumentos',
        link: 'misDocumentos',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 12,
        nombre: 'turnos',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'turno-bold',
        target: 'misTurnos',
        link: 'misTurnos',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 13,
        nombre: 'mensajes',
        tipo: 'info',
        semanticTag: 'otro',
        icono: 'mail',
        target: 'misMensajes',
        link: 'misMensajes',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 14,
        nombre: 'organizaciones',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'hospital',
        target: 'misOrganizaciones',
        link: 'misOrganizaciones',
        color: '#0070cc',
        outlet: 'listado',
    },
    {
        id: 9,
        nombre: 'equipo de salud',
        tipo: 'info',
        semanticTag: 'solicitud',
        icono: 'medico',
        target: 'miEquipo',
        link: 'miEquipo',
        color: '#0070cc',
        outlet: 'listado',
    },
];
