import { Solicitud } from "./solicitud";

export const SOLICITUDES: Solicitud[] = [
    {
        id: 432,
        fecha: "15/03/2021",
        servicio: 'Servicio de kinesiología',
        unidadOrganizativa: 'Huemul',
        organizacion: "Hospital Provincial Neuquén 'Dr. Eduardo Castro Rendón'",
        organizacionId: 1,
        paciente:
        {
            id: 6,
            documento: '38906735',
            cuil: '20-38906735-5',
            activo: true,
            estado: 'temporal',
            nombre: 'Marco Savino',
            apellido: 'Santarelli',
            nombreCompleto: '',
            alias: '',
            contacto: 2993420134,
            sexo: 'masculino',
            genero: 'masculino',
            fechaNacimiento: '20/09/1957',
            tipoIdentificacion: '',
            numeroIdentificacion: '',
            edad: 63,
            edadReal: 'null',
            fechaFallecimiento: null,
            domicilio: 'Las acacias 410',
            estadoCivil: undefined,
            foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
            relaciones: 'abuelo',
            financiador: 'ISSN',
            identificadores: 'null',
            claveBlocking: 'null',
            entidadesValidadoras: 'ISSN',
            scan: 'null',
            reportarError: false,
            notaError: '',
        },
        profesional: "Giardino, Walter",
        prestacion: "Consulta de neurología",
        organizacionOrigen: "Centro de Salud 'Las Lajas'",
        profesionalOrigen: "Barilari, Adrián",
        prestacionOrigen: "Consulta general de medicina",
        estado: "en curso",
        registros: false,
    },
    {
        id: 432,
        fecha: "15/03/2021",
        servicio: 'Servicio de kinesiología',
        unidadOrganizativa: 'Huemul',
        organizacion: "Hospital Provincial Neuquén 'Dr. Eduardo Castro Rendón'",
        organizacionId: 1,
        paciente:
        {
            id: 6,
            documento: '38906735',
            cuil: '20-38906735-5',
            activo: true,
            estado: 'temporal',
            nombre: 'Marco Savino',
            apellido: 'Santarelli',
            nombreCompleto: '',
            alias: '',
            contacto: 2993420134,
            sexo: 'masculino',
            genero: 'masculino',
            fechaNacimiento: '20/09/1957',
            tipoIdentificacion: '',
            numeroIdentificacion: '',
            edad: 63,
            edadReal: 'null',
            fechaFallecimiento: null,
            domicilio: 'Las acacias 410',
            estadoCivil: undefined,
            foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
            relaciones: 'abuelo',
            financiador: 'ISSN',
            identificadores: 'null',
            claveBlocking: 'null',
            entidadesValidadoras: 'ISSN',
            scan: 'null',
            reportarError: false,
            notaError: '',
        },
        profesional: "Giardino, Walter",
        prestacion: "Consulta de neurología",
        organizacionOrigen: "Centro de Salud 'Las Lajas'",
        profesionalOrigen: "Barilari, Adrián",
        prestacionOrigen: "Consulta general de medicina",
        estado: "en curso",
        registros: false,
    },
    {
        id: 432,
        fecha: "15/03/2021",
        servicio: 'Servicio de kinesiología',
        unidadOrganizativa: 'Huemul',
        organizacion: "Hospital Provincial Neuquén 'Dr. Eduardo Castro Rendón'",
        organizacionId: 1,
        paciente:
        {
            id: 6,
            documento: '38906735',
            cuil: '20-38906735-5',
            activo: true,
            estado: 'temporal',
            nombre: 'Marco Savino',
            apellido: 'Santarelli',
            nombreCompleto: '',
            alias: '',
            contacto: 2993420134,
            sexo: 'masculino',
            genero: 'masculino',
            fechaNacimiento: '20/09/1957',
            tipoIdentificacion: '',
            numeroIdentificacion: '',
            edad: 63,
            edadReal: 'null',
            fechaFallecimiento: null,
            domicilio: 'Las acacias 410',
            estadoCivil: undefined,
            foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
            relaciones: 'abuelo',
            financiador: 'ISSN',
            identificadores: 'null',
            claveBlocking: 'null',
            entidadesValidadoras: 'ISSN',
            scan: 'null',
            reportarError: false,
            notaError: '',
        },
        profesional: "Giardino, Walter",
        prestacion: "Consulta de neurología",
        organizacionOrigen: "Centro de Salud 'Las Lajas'",
        profesionalOrigen: "Barilari, Adrián",
        prestacionOrigen: "Consulta general de medicina",
        estado: "en curso",
        registros: false,
    },
    {
        id: 432,
        fecha: "15/03/2021",
        servicio: 'Servicio de kinesiología',
        unidadOrganizativa: 'Huemul',
        organizacion: "Hospital Provincial Neuquén 'Dr. Eduardo Castro Rendón'",
        organizacionId: 1,
        paciente:
        {
            id: 6,
            documento: '38906735',
            cuil: '20-38906735-5',
            activo: true,
            estado: 'temporal',
            nombre: 'Marco Savino',
            apellido: 'Santarelli',
            nombreCompleto: '',
            alias: '',
            contacto: 2993420134,
            sexo: 'masculino',
            genero: 'masculino',
            fechaNacimiento: '20/09/1957',
            tipoIdentificacion: '',
            numeroIdentificacion: '',
            edad: 63,
            edadReal: 'null',
            fechaFallecimiento: null,
            domicilio: 'Las acacias 410',
            estadoCivil: undefined,
            foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
            relaciones: 'abuelo',
            financiador: 'ISSN',
            identificadores: 'null',
            claveBlocking: 'null',
            entidadesValidadoras: 'ISSN',
            scan: 'null',
            reportarError: false,
            notaError: '',
        },
        profesional: "Giardino, Walter",
        prestacion: "Consulta de neurología",
        organizacionOrigen: "Centro de Salud 'Las Lajas'",
        profesionalOrigen: "Barilari, Adrián",
        prestacionOrigen: "Consulta general de medicina",
        estado: "en curso",
        registros: false,
    },
]