import { Paciente } from './paciente';

export const PACIENTES: Paciente[] = [
    {
        id: 1,
        documento: '36307632',
        cuil: '20-36307632-5',
        activo: true,
        estado: 'temporal',
        nombre: 'Fernanda Gabriela',
        apellido: 'Saralero Mercusi',
        nombreCompleto: 'Fernanda Agustina Sastre Maranelli',
        alias: '',
        contacto: 2993420134,
        sexo: undefined,
        genero: undefined,
        fechaNacimiento: '20/09/1992',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 27,
        edadReal: 'null',
        fechaFallecimiento: 'null',
        domicilio: 'Avenida San Juan 798',
        estadoCivil: undefined,
        foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
        relaciones: 'null',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    },
    {
        id: 2,
        documento: '21532632',
        cuil: '20-21532632-5',
        activo: true,
        estado: 'Validado',
        nombre: 'Pedro Ernesto',
        apellido: 'Martinez Valenzuela',
        nombreCompleto: '',
        alias: '',
        contacto: 2993420134,
        sexo: undefined,
        genero: undefined,
        fechaNacimiento: '11/09/1975',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 63,
        edadReal: 'null',
        fechaFallecimiento: '20/01/2020',
        domicilio: 'Avenida San Juan 798',
        estadoCivil: undefined,
        foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
        relaciones: 'null',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    },
    {
        id: 3,
        documento: '36307632',
        cuil: '20-36307632-5',
        activo: true,
        estado: 'temporal',
        nombre: 'Fernanda Agustina',
        apellido: 'Sastre Maranelli',
        nombreCompleto: 'Fernanda Agustina Sastre Maranelli',
        alias: '',
        contacto: 2993420134,
        sexo: undefined,
        genero: undefined,
        fechaNacimiento: '20/09/1992',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 27,
        edadReal: 'null',
        fechaFallecimiento: 'null',
        domicilio: 'Avenida San Juan 798',
        estadoCivil: undefined,
        foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
        relaciones: 'null',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    },
    {
        id: 4,
        documento: '12532632',
        cuil: '20-12532632-5',
        activo: true,
        estado: 'Validado',
        nombre: 'Ernesto Muriel',
        apellido: 'Valenzuela Della Gaspera',
        nombreCompleto: '',
        alias: '',
        contacto: 2993420134,
        sexo: undefined,
        genero: undefined,
        fechaNacimiento: '20/09/1957',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 63,
        edadReal: 'null',
        fechaFallecimiento: '23/11/2019',
        domicilio: 'Avenida San Juan 798',
        estadoCivil: undefined,
        foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
        relaciones: 'null',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    },
    {
        id: 5,
        documento: '36307632',
        cuil: '20-36307632-5',
        activo: true,
        estado: 'temporal',
        nombre: 'Agustina Alejandra',
        apellido: 'Jara Martino',
        nombreCompleto: 'Fernanda Agustina Sastre Maranelli',
        alias: '',
        contacto: 2993420134,
        sexo: undefined,
        genero: undefined,
        fechaNacimiento: '20/09/1992',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 27,
        edadReal: 'null',
        fechaFallecimiento: 'null',
        domicilio: 'Avenida San Juan 798',
        estadoCivil: undefined,
        foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
        relaciones: 'null',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    },
    {
        id: 6,
        documento: '38906735',
        cuil: '20-38906735-5',
        activo: true,
        estado: 'temporal',
        nombre: 'Marco Savino',
        apellido: 'Santarelli',
        nombreCompleto: '',
        alias: '',
        contacto: 2993420134,
        sexo: undefined,
        genero: undefined,
        fechaNacimiento: '20/09/1957',
        tipoIdentificacion: '',
        numeroIdentificacion: '',
        edad: 63,
        edadReal: 'null',
        fechaFallecimiento: 'null',
        domicilio: 'Las acacias 410',
        estadoCivil: undefined,
        foto: 'https://library.kissclipart.com/20180901/krw/kissclipart-user-thumbnail-clipart-user-lorem-ipsum-is-simply-bfcb758bf53bea22.jpg',
        relaciones: 'null',
        financiador: 'ISSN',
        identificadores: 'null',
        claveBlocking: 'null',
        entidadesValidadoras: 'ISSN',
        scan: 'null',
        reportarError: false,
        notaError: '',
    }
];