version: 2
jobs:
  install:
    working_directory: ~/app
    docker:
      - image: circleci/node:10-browsers
        environment:
          TZ: "America/Argentina/Buenos_Aires"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - app
  build:
    working_directory: ~/app
    environment:
          TZ: "America/Argentina/Buenos_Aires"
    docker:
      - image: circleci/node:10-browsers
        environment:
          TZ: "America/Argentina/Buenos_Aires"
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: commit lint
          command: npm run commitlint-circle
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:ci
      - run:
          name: build
          command: npm run build -- --configuration=production --progress=false

  cypress:
    working_directory: ~/app
    environment:
      TZ: "America/Argentina/Buenos_Aires"
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm 
          TZ: "America/Argentina/Buenos_Aires"
    steps:
      - attach_workspace:
          at: ~/ 
      - run:
          name: CYPRESS
          command: APPLITOOLS_PARENT_BRANCH_NAME=master APPLITOOLS_BRANCH_NAME=$CIRCLE_BRANCH npm run test:cypress

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:10-browsers
        environment:
          TZ: "America/Argentina/Buenos_Aires"
    steps:
      - attach_workspace:
          at: ~/
      - run: npx semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build:
          requires:
            - install
      - cypress:
          requires:
            - install
      - request-deploy:
          type: approval
          requires:
            - build
            - cypress
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - request-deploy
          filters:
            branches:
              only: master

