import { Component } from '@angular/core';

@Component({
    selector: 'plex-icon-demo',
    templateUrl: 'icon.html',
    styles: [`

       span {
            height: 32px;
            width: 32px;
            margin: 5px;
            background-color: lightcyan;
            border: solid 1px black;
        }

    `]

})
export class DemoIconComponent {

    icons = [
        'close',
        'account',
        'account-multiple',
        'phone-plus',
        'file-multiple',
        'delete',
        'information-variant',
        'settings',
        'chevron-left',
        'chevron-right',
        'plus',
        'calendar-plus',
        'open-in-app',
        'calendar-multiple',
        'cellphone-android',
        'pencil',
        'clock',
        'history',
        'folder-account',
        'magnify',
        'account-card-details',
        'calendar-clock',
        'account-search',
        'account-multiple-plus',
        'account-off',
        'account-details',
        'undo',
        'contacts',
        'check',
        'calendar',
        'close-circle-outline',
        'mdi-content-save',
        'home-plus',
        'arrow-left',
        'trash-can',
        'plus-circle',
        'account-plus',
        'spray',
        'lock',
        'lock-open',
        'arrow-down-box',
        'arrow-up-box',
        'information-outline',
        'information',
        'download',
        'link-variant',
        'playlist-plus',
        'arrow-down-drop-circle-outline',
        'google-chrome',
        'firefox',
        'alert-circle-outline',
        'account-alert',
        'star',
        'star-outline',
        'message-bulleted',
        'comment',
        'checkbox-marked',
        'checkbox-blank-outline',
        'account-remove',
        'account-check',
        'account-switch',
        'folder-account',
        'comment-outline',
        'account-off',
        'stop',
        'emoticon-happy',
        'message',
        'arrow-left',
        'check',
        'pencil',
        'refresh',
        'alert-outline',
        'arrow-up-bold-circle-outline',
        'arrow-up-bold-circle',
        'delete',
        'pause',
        'sync-alert',
        'content-copy',
        'play',
        'account-plus',
        'format-list-checks',
        'printer',
        'calendar-today',
        'hospital',
        'account',
        'message-alert',
        'message-text-outline',
        'message-processing',
        'emoticon-sad',
        'clock',
        'timelapse',
        'check-circle',
        'key',
        'backup-restore',
        'routes',
        'sign-direction',
        'account-convert',
        'arrow-down-drop-circle-outline',
        'arrow-up-drop-circle-outline',
        'eye',
        'eye-off',
        'emoticon',
        'account-card-details',
        'map-marker',
        'information-outline',
        'close-box',
        'information',
        'calendar-clock',
        'account-outline',
        'close-circle',
        'content-save',
        'account-star',
        'barcode-scan',
        'alert',
        'lock-alert',
        'chevron-double-left',
        'chevron-double-right',
        'account-search',
        'checkbox-blank-circle-outline',
        'share',
        'plus',
        'file-pdf',
        'folder-remove',
        'clipboard-arrow-left',
        'file-tree',
        'close',
        'chevron-down',
        'clipboard-account',
        'account-multiple-outline',
        'calendar',
        'contacts',
        'folder',
        'hotel',
        'account-key',
        'chart-line',
        'poll',
        'dialpad',
        'help-circle',
        'format-list-bulleted',
        'crop-square',
        'view-list',
        'gender-male-female',
        'gender-male',
        'gender-female',
        'calendar-multiple',
        'timetable',
        'clipboard-check-outline',
        'flask-empty-outline',
        'eyedropper-variant',
        'magnify',
        'chevron-up',
        'drag-vertical',
        'menu-down',
        'menu-up',
        'chevron-left',
        'link-variant-off',
        'plus-circle',
        'delete-empty',
        'chevron-right',
    ];

}
